dist: xenial
language: c++
c++:
  - g++-7
  - g++-8
sudo: required
git:
  depth: false
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxdo-dev
      - libinput-tools
install:
  - bash install
script:
  - ./tests/run_tests
after_script:
  - bash uninstall
